## Задание 1

Случайная непрерывная величина A имеет равномерное распределение на промежутке (200, 800].
Найдите ее среднее значение и дисперсию.

In [1]:
aA = 200
bA = 800
MA = (aA+bA)/2
MA

500.0

In [2]:
sigmaA = ((bA-aA)**2)/12
sigmaA

30000.0

## Задание 2

О случайной непрерывной равномерно распределенной величине B известно, что ее дисперсия равна 0.2.
Можно ли найти правую границу величины B и ее среднее значение зная, что левая граница равна 0.5?
Если да, найдите ее.

In [5]:
sigmaB = 0.2
aB = 0.5


In [6]:
from math import sqrt

In [7]:
bB1 = sqrt (12*sigmaB)+aB
bB2 = - sqrt (12*sigmaB)+aB
bB1


2.049193338482967

In [8]:
bB2

-1.0491933384829668

In [11]:
if bB1 > aB:
    print (f'правая границы величины B равна {bB1}, а ее среднее значение равно {(aB+bB1)/2}')
elif bB2 > aB:
    print (f'правая границы величины B равна {bB2}, а ее среднее значение равно {(aB+bB2)/2}')

правая границы величины B равна 2.049193338482967, а ее среднее значение равно 1.2745966692414834


## Задание 3

Непрерывная случайная величина X распределена нормально и задана плотностью распределения
f(x) = (1 / (4 * sqrt(2*pi))) * (exp(-(x+2)**2) / 32).
Найдите:
а). M(X)
б). D(X)
в). std(X) (среднее квадратичное отклонение)

обратимся к функции нормального распределения и выберем из заданной формулы значения, при котором заданная функция нормально распределена 

* M(X) = -2
* std(X) = 4
* D(x) = 16

## Задание 4

Рост взрослого населения города X имеет нормальное распределение.
Причем, средний рост равен 174 см, а среднее квадратичное отклонение равно 8 см.
Какова вероятность того, что случайным образом выбранный взрослый человек имеет рост:


In [14]:
mX = 174
stdX = 8

 а). больше 182 см

In [15]:
Z1 = (182-mX)/stdX
Z1


1.0

In [19]:
P1 = 1 - 0.84134
print (f'вероятность того, что рост выбранного человека будет больше 182 см равна {P1}')

вероятность того, что рост выбранного человека будет больше 182 см равна 0.15866000000000002


б). больше 190 см

In [21]:
Z2 = (190-mX)/stdX
Z2

2.0

In [22]:
P2 = 1 - 0.97725
print (f'вероятность того, что рост выбранного человека будет больше 190 см равна {P2}')

вероятность того, что рост выбранного человека будет больше 190 см равна 0.022750000000000048


в). от 166 см до 190 см

In [24]:
Z3 = (166-mX)/stdX
Z3

-1.0

In [28]:
P3 = 1 - 0.1587
print (f'вероятность того, что рост выбранного человека будет больше 166 см но меньше 190 равна {P3 - P2}')

вероятность того, что рост выбранного человека будет больше 166 см но меньше 190 равна 0.8185499999999999


г). от 166 см до 182 см

In [30]:
print (f'вероятность того, что рост выбранного человека будет от 166 до 182 см равна {P3 - P1}')

вероятность того, что рост выбранного человека будет от 166 до 182 см равна 0.6826399999999999


д) от 158 до 190

In [32]:
Z4 = (158-mX)/stdX
Z4

-2.0

In [33]:
P4 = 1-0.0228
print (f'вероятность того, что рост выбранного человека будет от 158 до 190 см равна {P4 - P2}')

вероятность того, что рост выбранного человека будет от 158 до 190 см равна 0.9544499999999999


е). не выше 150 см или не ниже 190 см

In [34]:
Z5 = (150-mX)/stdX
Z5

-3.0

In [37]:
P5 = 0.0013
print (f'вероятность того, что рост выбранного человека будет не выше 150 или не ниже 190 см равна {P5+P2}')

вероятность того, что рост выбранного человека будет не выше 150 или не ниже 190 см равна 0.024050000000000047


ё). не выше 150 см или не ниже 198 см

In [38]:
Z6 = (198-mX)/stdX
Z6

3.0

In [39]:
P6 = 1- 0.99865
print (f'вероятность того, что рост выбранного человека будет не выше 150 или не ниже 198 см равна {P5+P6}')

вероятность того, что рост выбранного человека будет не выше 150 или не ниже 198 см равна 0.0026499999999999623


ж). ниже 166 см.

In [41]:
print (f'вероятность того, что рост выбранного человека будет ниже 166 см  {1 -P3}')

вероятность того, что рост выбранного человека будет ниже 166 см  0.15870000000000006


## Задание 5

На сколько сигм (средних квадратичных отклонений) отклоняется рост человека, равный 190 см, от
математического ожидания роста в популяции, в которой M(X) = 178 см и D(X) = 25 кв.см?

In [44]:
Z = (190 - 178)/5
Z

2.4